### ISSUE TITLE
CSS style for some nested width-100 class is missing

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/czr-base-fmk#2]
I can see we have:
```css
.width-100 .czr-input, .czr-sub-set .customize-control-title.width-100 {
  width: 100%;
}
```
https://github.com/presscustomizr/czr-base-fmk/blob/master/assets/css/czr-ccat-control-base.css#L1044

But our templates also produce this kind of structure:
```html
<div class="czr-sub-set width-100" data-input-type="textarea">
    <div class="customize-control-title ">Heading text</div>
    <div class="czr-input ">
        <textarea data-czrtype="heading_text" class="width-100" name="textarea" rows="10" cols=""> 
        </textarea>
     </div>
</div>
```
In this case the .customize-control-title and the textarea to not go fullwidth as they do not match the above CSS rules.
